### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by smurn** [JesusFreke/fusionIdea#5]
I really like the idea of this plug-in, but I can't seem to get it to work. 

For example, I can't find "Open Module Settings" anywhere in PyCharm (community or commercial edition) 2018.3.4. 

The "Installation" section in the Readme gives instructions for a small add-in, but the next section "Add-in" seems to state that this small add-in is not actually required? 

The "Go to File -> Scripts and Add-Ins" instruction also doesn't fit PyCharm, I think. I can install Plugins, but not Add-ins, as far as I can see.

**Comment by JesusFreke** [comment]
I was a bit confused at first, because I *knew* I had removed that blurb in the readme about the addon, and added some better documentation for pycharm.

Looks like I forgot to push some commits :)

Take a look at the current README now, and feel free to let me know if you find anything incorrect/missing/misleading/untruthful/malicious or otherwise unsuitable.

**Comment by JesusFreke** [comment]
Oh, I think I see what I did. When I did the v0.5.3 and v0.5.4 releases, it looks like I *just* pushed the tag, but didn't actually update master.

**Comment by smurn** [comment]
That was a fast response! Yes, this is much clearer. 

I ended up finding that PyCharm option, but something is still amiss. When making calls to Fusion's API, it seems to invoke some dummy implementation instead of actually connecting to Fusion 360. It might be related to https://github.com/JesusFreke/fusionIdea/issues/2, I remember seeing that error at some point. I'll have to investigate some more. Not in the scope of this issue though, so I'm resolving this one.

I did get it to run in IDEA just fine. Such step up from Spyder! Works beautifully. Thanks so much!

**Comment by JesusFreke** [comment]
Yeah, I admittedly don't use PyCharm myself, so there may be some lurking issues that I haven't noticed, since I really only use it from IDEA. I honestly didn't realize at first that pycharm was so much different. The whole lack of modules thing and the different settings structures took me a bit by surprise. I had assumed it would basically just be a version of IDEA with only the python language plugin, and other supporting plugins.
