### ISSUE TITLE
stdout truncated after 1000 bytes

### ISSUE THREAD

**Issue by smurn** [JesusFreke/fusionIdea#6]
I don't know if this is really an issue with the plugin or a fusion 360 limitation, but it seems that the standard output is truncated to 999 bytes and `...` is appended, if the output is larger than 1000 bytes.

```
import sys
def run(context):
    for i in range(1000):
        sys.stdout.write("o")
    sys.stdout.write("x")
```

this will end in `oooo...`. But if you reduce it to 999 bytes, then it will end in `oooox`. This also happens if the output is split into multiple lines. The total number of bytes in the stdout is limited.

I've tried `sys.stdout.flush()` at the end, but it did not change the result.

**Comment by JesusFreke** [comment]
I've run into this myself. The problem seems to be the buffer size used by some of IDEA's python code used for communication between the target process and the IDE.

As a workaround, you can add this at the top of your script, to increase the buffer size.

import _pydevd_bundle.pydevd_comm
_pydevd_bundle.pydevd_comm.MAX_IO_MSG_SIZE = 131072


I'll see if there's somewhere I can inject this with the plugin itself, because the default 1000 bytes does seem too small, especially with long python stack traces.

**Comment by smurn** [comment]
Thank you! This works perfectly.

**Comment by JesusFreke** [comment]
This is built into the plugin now, as of 0.5.7
