### ISSUE TITLE
Starts with wrong interpreter

### ISSUE THREAD

**Issue by Jerakin** [JesusFreke/fusionIdea#9]
On Windows in PyCharm when I `Run in Fusion 360` it does not start it with the same interpreter that is setup in the settings (`Project: <name> -> Project Interpreter`). In my case it runs with (the most recent) 3.7 but I want to run it with 3.5.

**Comment by JesusFreke** [comment]
Fusion 360 scripts must run inside the python environment that is running inside the fusion 360 process. And for the current versions of Fusion 360, that is a Python 3.7 enviroment.

Changing the interpreter in the project/module only affects IDEA's/PyCharm's syntax highlighting, autocompletion and such.

**Comment by Jerakin** [comment]
Ah! I thought it was running on 3.5.3 (can't remember where I saw that version) so that's what I tried to dev on. :)

**Comment by JesusFreke** [comment]
What I usually do is to set up a python interpreter that points directly to the Python interpreter that is bundled with Fusion 360.

The big downside to this though is that I have to re-setup the interpreter every time fusion is upgraded, since the path changes.

The plugin currently has functionality to detect when fusion is upgraded and to switch the fusion api library and the path to the fusion executable and such. I've thought about adding in some logic there that also switches the interpreter, if one is set up that points to a fusion directory.

**Comment by JesusFreke** [comment]
And yeah, it used to be 3.5 :)

It was just recently changed, when they moved from Spyder to VSCode.
